// flow-typed signature: eee23f8f4226b6966c244856bd584114
// flow-typed version: <<STUB>>/nlf_v^1.4.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nlf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nlf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nlf/bin/nlf-cli' {
  declare module.exports: any;
}

declare module 'nlf/gulpfile' {
  declare module.exports: any;
}

declare module 'nlf/lib/compare-module-names' {
  declare module.exports: any;
}

declare module 'nlf/lib/file-source' {
  declare module.exports: any;
}

declare module 'nlf/lib/formatters/csv' {
  declare module.exports: any;
}

declare module 'nlf/lib/formatters/standard' {
  declare module.exports: any;
}

declare module 'nlf/lib/license-collection' {
  declare module.exports: any;
}

declare module 'nlf/lib/license-find' {
  declare module.exports: any;
}

declare module 'nlf/lib/module' {
  declare module.exports: any;
}

declare module 'nlf/lib/nlf' {
  declare module.exports: any;
}

declare module 'nlf/lib/package-source' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nlf/bin/nlf-cli.js' {
  declare module.exports: $Exports<'nlf/bin/nlf-cli'>;
}
declare module 'nlf/gulpfile.js' {
  declare module.exports: $Exports<'nlf/gulpfile'>;
}
declare module 'nlf/index' {
  declare module.exports: $Exports<'nlf'>;
}
declare module 'nlf/index.js' {
  declare module.exports: $Exports<'nlf'>;
}
declare module 'nlf/lib/compare-module-names.js' {
  declare module.exports: $Exports<'nlf/lib/compare-module-names'>;
}
declare module 'nlf/lib/file-source.js' {
  declare module.exports: $Exports<'nlf/lib/file-source'>;
}
declare module 'nlf/lib/formatters/csv.js' {
  declare module.exports: $Exports<'nlf/lib/formatters/csv'>;
}
declare module 'nlf/lib/formatters/standard.js' {
  declare module.exports: $Exports<'nlf/lib/formatters/standard'>;
}
declare module 'nlf/lib/license-collection.js' {
  declare module.exports: $Exports<'nlf/lib/license-collection'>;
}
declare module 'nlf/lib/license-find.js' {
  declare module.exports: $Exports<'nlf/lib/license-find'>;
}
declare module 'nlf/lib/module.js' {
  declare module.exports: $Exports<'nlf/lib/module'>;
}
declare module 'nlf/lib/nlf.js' {
  declare module.exports: $Exports<'nlf/lib/nlf'>;
}
declare module 'nlf/lib/package-source.js' {
  declare module.exports: $Exports<'nlf/lib/package-source'>;
}
