// flow-typed signature: c0dfec5b9235455d6f1c94bece716b63
// flow-typed version: <<STUB>>/nodely_v^0.0.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodely'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodely' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodely/lib/actions' {
  declare module.exports: any;
}

declare module 'nodely/lib/index' {
  declare module.exports: any;
}

declare module 'nodely/lib/master' {
  declare module.exports: any;
}

declare module 'nodely/lib/types' {
  declare module.exports: any;
}

declare module 'nodely/lib/worker' {
  declare module.exports: any;
}

declare module 'nodely/src/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'nodely/src/__tests__/worker-test' {
  declare module.exports: any;
}

declare module 'nodely/src/actions' {
  declare module.exports: any;
}

declare module 'nodely/src/index' {
  declare module.exports: any;
}

declare module 'nodely/src/master' {
  declare module.exports: any;
}

declare module 'nodely/src/types' {
  declare module.exports: any;
}

declare module 'nodely/src/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodely/lib/actions.js' {
  declare module.exports: $Exports<'nodely/lib/actions'>;
}
declare module 'nodely/lib/index.js' {
  declare module.exports: $Exports<'nodely/lib/index'>;
}
declare module 'nodely/lib/master.js' {
  declare module.exports: $Exports<'nodely/lib/master'>;
}
declare module 'nodely/lib/types.js' {
  declare module.exports: $Exports<'nodely/lib/types'>;
}
declare module 'nodely/lib/worker.js' {
  declare module.exports: $Exports<'nodely/lib/worker'>;
}
declare module 'nodely/src/__tests__/index-test.js' {
  declare module.exports: $Exports<'nodely/src/__tests__/index-test'>;
}
declare module 'nodely/src/__tests__/worker-test.js' {
  declare module.exports: $Exports<'nodely/src/__tests__/worker-test'>;
}
declare module 'nodely/src/actions.js' {
  declare module.exports: $Exports<'nodely/src/actions'>;
}
declare module 'nodely/src/index.js' {
  declare module.exports: $Exports<'nodely/src/index'>;
}
declare module 'nodely/src/master.js' {
  declare module.exports: $Exports<'nodely/src/master'>;
}
declare module 'nodely/src/types.js' {
  declare module.exports: $Exports<'nodely/src/types'>;
}
declare module 'nodely/src/worker.js' {
  declare module.exports: $Exports<'nodely/src/worker'>;
}
