// flow-typed signature: 772f93863f12a3100eabddbd13d04dec
// flow-typed version: <<STUB>>/versiony_v^2.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'versiony'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'versiony' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'versiony/lib/index' {
  declare module.exports: any;
}

declare module 'versiony/lib/logger' {
  declare module.exports: any;
}

declare module 'versiony/lib/model' {
  declare module.exports: any;
}

declare module 'versiony/lib/utils' {
  declare module.exports: any;
}

declare module 'versiony/tests/end-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/from-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/get-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/get-version-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/major-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/minor-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/new-major-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/new-minor-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/patch-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/pre-release-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/to-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/utils' {
  declare module.exports: any;
}

declare module 'versiony/tests/version-spec' {
  declare module.exports: any;
}

declare module 'versiony/tests/with-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'versiony/lib/index.js' {
  declare module.exports: $Exports<'versiony/lib/index'>;
}
declare module 'versiony/lib/logger.js' {
  declare module.exports: $Exports<'versiony/lib/logger'>;
}
declare module 'versiony/lib/model.js' {
  declare module.exports: $Exports<'versiony/lib/model'>;
}
declare module 'versiony/lib/utils.js' {
  declare module.exports: $Exports<'versiony/lib/utils'>;
}
declare module 'versiony/tests/end-spec.js' {
  declare module.exports: $Exports<'versiony/tests/end-spec'>;
}
declare module 'versiony/tests/from-spec.js' {
  declare module.exports: $Exports<'versiony/tests/from-spec'>;
}
declare module 'versiony/tests/get-spec.js' {
  declare module.exports: $Exports<'versiony/tests/get-spec'>;
}
declare module 'versiony/tests/get-version-spec.js' {
  declare module.exports: $Exports<'versiony/tests/get-version-spec'>;
}
declare module 'versiony/tests/major-spec.js' {
  declare module.exports: $Exports<'versiony/tests/major-spec'>;
}
declare module 'versiony/tests/minor-spec.js' {
  declare module.exports: $Exports<'versiony/tests/minor-spec'>;
}
declare module 'versiony/tests/new-major-spec.js' {
  declare module.exports: $Exports<'versiony/tests/new-major-spec'>;
}
declare module 'versiony/tests/new-minor-spec.js' {
  declare module.exports: $Exports<'versiony/tests/new-minor-spec'>;
}
declare module 'versiony/tests/patch-spec.js' {
  declare module.exports: $Exports<'versiony/tests/patch-spec'>;
}
declare module 'versiony/tests/pre-release-spec.js' {
  declare module.exports: $Exports<'versiony/tests/pre-release-spec'>;
}
declare module 'versiony/tests/to-spec.js' {
  declare module.exports: $Exports<'versiony/tests/to-spec'>;
}
declare module 'versiony/tests/utils.js' {
  declare module.exports: $Exports<'versiony/tests/utils'>;
}
declare module 'versiony/tests/version-spec.js' {
  declare module.exports: $Exports<'versiony/tests/version-spec'>;
}
declare module 'versiony/tests/with-spec.js' {
  declare module.exports: $Exports<'versiony/tests/with-spec'>;
}
